site_name: Documentation
theme:
  name: material
  palette:
    primary: deep purple

markdown_extensions:
  - abbr
  - footnotes
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: On this page
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  
extra_css:
  - stylesheets/extra.css